server:
  port: 8765
  
zuul:
  sensitiveHeaders: "Cookie,Set-Cookie,Authorization" # propagate special headers like token and security
  ignoredServices: "*"
  prefix: /api
  routes:
    client-test:
      path: /client-test/**
      serviceId: client-test
    client-edge:
      path: /client-edge/**
      serviceId: client-edge

ribbon:
  ConnectTimeout: 3000
  ReadTimeOut: 30000
  eureka:
    enabled: true

eureka:
  instance:
    appname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

swagger:
  config:
    refreshrate: 5000
